--------------------------------------------------------
--  파일이 생성됨 - 화요일-1월-27-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DAILY_ANALYSIS
--------------------------------------------------------

  CREATE TABLE "SOLDESK"."DAILY_ANALYSIS" 
   (	"ANALYSIS_ID" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"ANALYSIS_DATE" DATE, 
	"DAILY_SCORE" NUMBER, 
	"ACTIVE_SCORE" NUMBER, 
	"GAME_SCORE_AVG" NUMBER, 
	"STATUS_LEVEL" VARCHAR2(10 BYTE), 
	"IS_SAVE_BOOL" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007719
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOLDESK"."SYS_C007719" ON "SOLDESK"."DAILY_ANALYSIS" ("ANALYSIS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_DAILY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOLDESK"."UQ_DAILY" ON "SOLDESK"."DAILY_ANALYSIS" ("USER_ID", "ANALYSIS_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DAILY_ANALYSIS
--------------------------------------------------------

  ALTER TABLE "SOLDESK"."DAILY_ANALYSIS" ADD PRIMARY KEY ("ANALYSIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SOLDESK"."DAILY_ANALYSIS" ADD CONSTRAINT "UQ_DAILY" UNIQUE ("USER_ID", "ANALYSIS_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DAILY_ANALYSIS
--------------------------------------------------------

  ALTER TABLE "SOLDESK"."DAILY_ANALYSIS" ADD CONSTRAINT "FK_ANALYSIS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SOLDESK"."USERS" ("USER_ID") ENABLE;
