--------------------------------------------------------
--  파일이 생성됨 - 화요일-1월-27-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GAME_LOG
--------------------------------------------------------

  CREATE TABLE "SOLDESK"."GAME_LOG" 
   (	"GAME_ID" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"GAME_TYPE" VARCHAR2(30 BYTE), 
	"GAME_LEVEL" VARCHAR2(10 BYTE), 
	"SCORE" NUMBER, 
	"PLAY_TIME" VARCHAR2(10 BYTE), 
	"PLAYED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007717
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOLDESK"."SYS_C007717" ON "SOLDESK"."GAME_LOG" ("GAME_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GAME_LOG
--------------------------------------------------------

  ALTER TABLE "SOLDESK"."GAME_LOG" ADD PRIMARY KEY ("GAME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GAME_LOG
--------------------------------------------------------

  ALTER TABLE "SOLDESK"."GAME_LOG" ADD CONSTRAINT "FK_GAME_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SOLDESK"."USERS" ("USER_ID") ENABLE;
