--------------------------------------------------------
--  파일이 생성됨 - 화요일-1월-27-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SOLDESK"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"LINKED_USER_ID" VARCHAR2(20 BYTE), 
	"SURVEY_TYPE" VARCHAR2(5 BYTE), 
	"SURVEY_SCORE" NUMBER, 
	"SURVEY_DATE" DATE, 
	"FCM_TOKEN" VARCHAR2(500 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007711
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOLDESK"."SYS_C007711" ON "SOLDESK"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007712
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOLDESK"."SYS_C007712" ON "SOLDESK"."USERS" ("LOGIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SOLDESK"."USERS" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SOLDESK"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SOLDESK"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SOLDESK"."USERS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SOLDESK"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SOLDESK"."USERS" ADD CHECK (role IN ('환자', '보호자')) ENABLE;
  ALTER TABLE "SOLDESK"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SOLDESK"."USERS" ADD UNIQUE ("LOGIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
